name: Update callsigns

on:
  schedule:
    - cron: '30 * * * 1-5'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install gspread oauth2client pandas requests 

      - name: Generate callsign html
        env:
          CALLSIGN: ${{ secrets.CALLSIGN }}
          PAGEID: ${{ vars.PAGEID }}
        run: python dynamic_callsign.py
       - name: Commit and push changes
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add callsign.html
          
           # Only commit and push if the file actually changed to avoid workflow errors
           git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto-update output.txt" && git push)